### ISSUE TITLE
Communication with database.

### ISSUE THREAD

**Issue by clahsu** [holozene/characterize.quest#2]
https://www.w3schools.com/nodejs/nodejs_mysql_insert.asp
JDBC

**Comment by clahsu** [comment]
1. Load set of components from database
2. Load specific character sheet from database
3. Send changes from classes to remote database (does not need to close connection)

**Comment by holozene** [comment]
- [ ] find out how the aws database is available
- [ ] write/implement php and scripting to make connection securely
- [ ] connect in theory
- [ ] test with an actual table and class (probably Component)

**Comment by holozene** [comment]
required reworking the entire project structure just in order to import Amplify.API
at least it looks cooler/more professional
#11

**Comment by holozene** [comment]
next, _using_ the api

**Comment by holozene** [comment]
having issues with creating new character db entry

**Comment by holozene** [comment]
works!
# eb27fb66c5adbc16162382f4392fbc136c94e0c6
